baseURL = 'https://neoforged.net/'
languageCode = 'en-us'
title = 'The NeoForged project'
theme = ["hugo-notice", "mainroad"]

[Params]
  description = "Files, news and information from the NeoForged Project" # Description of your site
  opengraph = true
  twitter_cards = true
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["author", "date", "categories"] # Order of post meta information
  images = ["img/authors/neoforged.png", "img/content/branding/banner.png"]
  mainSections = ["news", "blog"]

[Params.logo]
  image = "img/content/branding/banner.png"
  alt = "The NeoForged Project logo"
  subtitle = "Files, News and information from the NeoForged Project" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "social", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  cached = true
  twitter = "NeoForged_MC"

[[Params.widgets.social.custom]]
  title = "NeoForged Project Listing"
  url = "https://projects.neoforged.net/"
  icon = "svg/projects.svg"

[[Params.widgets.social.custom]]
  title = "GitHub"
  url = "https://github.com/neoforged/"
  icon = "svg/github.svg"

[[Params.widgets.social.custom]]
  title = "Discord"
  url = "https://discord.neoforged.net/"
  icon = "svg/discord.svg"

[[Params.widgets.social.custom]]
  title = "Open Collective"
  url = "https://opencollective.com/neoforged"
  icon = "svg/opencollective.svg"

[[Params.widgets.social.custom]]
  title = "Current backend service status"
  url = "https://status.neoforged.net"
  icon = "svg/time.svg"

[[Params.widgets.social.custom]]
  title = "Documentation"
  url = "https://docs.neoforged.net"
  icon = "svg/files.svg"

[[Params.widgets.social.custom]]
  title = "Order a server from CreeperHost"
  url = "https://www.creeperhost.net/partner/neoforge-aww"
  icon = "svg/creeperhost.svg"

[[Params.widgets.social.custom]]
  title = "Team member application form"
  url = "https://links.neoforged.net/apply"
  icon = "svg/team.svg"

[[Params.widgets.social.custom]]
  title = "Discord ban appeal form"
  url = "https://links.neoforged.net/appeal"
  icon = "svg/email.svg"
